"""
Pydantic models for Boomi MCP Server.

These models provide type safety and validation for all MCP tool operations.
"""

from .integration_models import (
    IntegrationSpecV1,
    IntegrationComponentSpec,
)
from .process_component import (
    ProcessAuthoringUnitV1,
    ProcessComponentEnvelopeV1,
    ProcessConnectionOverrideV1,
    ProcessExtensionBindingsV1,
    ProcessOverrideFieldV1,
)
from .pipeline_models import (
    PipelineSpec,
    StageSpec,
    PipelineEdgeSpec,
    PipelineStageKind,
    PipelineEdgeKind,
    StageCardinality,
    StageContextEffect,
    StageSideEffect,
    StageFailureBehavior,
)
from .process_ir_authoring import (
    PROCESS_IR_AUTHORING_CONTRACT_VERSION,
    ProcessIRAuthoringContractEntryV1,
    ProcessIRAuthoringContractPageV1,
    process_ir_authoring_contract_v1_json_schema,
)
from .process_ir import (
    PROCESS_IR_V1_CAPABILITIES,
    PROCESS_IR_VERSION,
    BranchLegV1,
    BranchNodeV1,
    CacheGetNodeV1,
    CachePutNodeV1,
    CacheRemoveNodeV1,
    CombineDocumentsOpV1,
    ComponentRefV1,
    ConnectorCallNodeV1,
    CurrentPropertySourceV1,
    CustomScriptingOpV1,
    DataProcessNodeV1,
    DataProcessOperationV1,
    DdpPropertySourceV1,
    DecisionFalseArmV1,
    DecisionNodeV1,
    DecisionOperandV1,
    DecisionTrueArmV1,
    DocumentCacheRetrieveNodeV1,
    DppPropertySourceV1,
    ErrorScopeV1,
    ExceptionNodeV1,
    FlowControlNodeV1,
    IdempotencyContractRefV1,
    IdempotencyEvidenceV1,
    KeyReferenceIdempotencyV1,
    LinearNodeV1,
    MapRefNodeV1,
    MessageNodeV1,
    ProcessCallNodeV1,
    ProcessIRDiagnostic,
    ProcessIRV1,
    ProcessIRValidationError,
    ProcessNodeV1,
    ProfilePropertySourceV1,
    PropertySourceV1,
    RetryPolicyV1,
    ReturnDocumentsNodeV1,
    SequenceNodeV1,
    SetDdpNodeV1,
    SetDppNodeV1,
    SourceEndpointV1,
    SplitDocumentsOpV1,
    StaticOperandV1,
    StaticPropertySourceV1,
    StopNodeV1,
    TargetEndpointV1,
    TrackOperandV1,
    TryCatchBodyStepV1,
    TryCatchCatchBodyV1,
    TryCatchNodeV1,
    TryCatchTryBodyV1,
    VerifiedActionIdempotencyV1,
    canonical_process_ir_json,
    canonical_process_ir_schema_json,
    parse_process_ir_v1,
    process_ir_v1_json_schema,
)

# SystemTopologySpecV1 (issue #144). The PLANNER lives in
# boomi_mcp.compiler.system_topology and is deliberately NOT exported here:
# boomi_mcp.models is the authored-contract surface, and re-exporting a planner
# through it is how a compiler internal ends up in an LLM-facing schema.
from .system_topology import (
    SYSTEM_TOPOLOGY_VERSION,
    TOPOLOGY_OBJECT_KINDS,
    TOPOLOGY_RELATION_KINDS,
    TOPOLOGY_RELATION_ROLES,
    ApiServiceObjectV1,
    ApiServiceRouteRelationV1,
    DeploymentBindingRelationV1,
    DeploymentUnitObjectV1,
    DocumentCacheObjectV1,
    DocumentCacheUseRelationV1,
    EnvironmentObjectV1,
    EventStreamReferenceRelationV1,
    ExternalEventStreamObjectV1,
    ExternalQueueObjectV1,
    OpaquePlatformRefV1,
    ProcessCallRelationV1,
    ProcessObjectV1,
    ProcessPropertyObjectV1,
    ProcessPropertyUseRelationV1,
    QueueReferenceRelationV1,
    RuntimeObjectV1,
    ScheduleBindingRelationV1,
    ScheduleObjectV1,
    SystemTopologyDiagnostic,
    SystemTopologySpecV1,
    SystemTopologyValidationError,
    TopologyComponentRefV1,
    TopologyObjectKeyV1,
    TopologyObjectV1,
    TopologyRelationKeyV1,
    TopologyRelationV1,
    canonical_system_topology_json,
    canonical_system_topology_schema_json,
    parse_system_topology_v1,
    system_topology_v1_json_schema,
)

# Typed recipe contributions (issue #145). Same rule as the two families above:
# this is the authored-CONTRACT surface, so the models and their parse/canonical
# helpers are exported and the ``boomi_mcp.recipes`` package — descriptor
# registry, composer, engine — deliberately is NOT. A recipe registry reached
# through ``boomi_mcp.models`` is a mutation surface in an authoring namespace.
from .recipe_contributions import (
    RECIPE_COMPONENT_TYPES,
    RECIPE_CONTRIBUTION_KINDS,
    RECIPE_CONTRIBUTION_VERSION,
    RECIPE_EXCLUDED_COMPONENT_TYPES,
    AddTopologyObjectV1,
    AddTopologyRelationV1,
    AppendRootTerminalLegV1,
    ComponentContributionV1,
    ConstraintCheckV1,
    ConstraintRequirementV1,
    InsertRootLinearStepV1,
    ProcessIRPatchOperationV1,
    ProcessIRPatchV1,
    RecipeComponentKey,
    RecipeComponentType,
    RecipeContributionV1,
    RecipeContributionValidationError,
    RecipeSemanticId,
    RequireCapabilityV1,
    RequireComponentV1,
    RequireProcessV1,
    RequireTopologyObjectV1,
    RequireTopologyRelationV1,
    SetProcessRootV1,
    SystemTopologyPatchOperationV1,
    SystemTopologyPatchV1,
    canonical_recipe_contribution_json,
    canonical_recipe_contribution_schema_json,
    canonical_recipe_contributions_json,
    parse_recipe_contribution,
    recipe_contribution_v1_json_schema,
    scan_forbidden_recipe_shape,
    validate_contribution_object,
)

# MCP authoring contracts (issue #146). Same rule as the three families above:
# this is the authored-CONTRACT surface, so the request/result models and their
# schema helpers are exported and the ORCHESTRATION — boomi_mcp.authoring, which
# resolves references, runs recipes and calls the compiler — deliberately is NOT.
from .authoring_workflow import (
    AUTHORING_ACTIONS,
    AUTHORING_CONTRACT_VERSION,
    AUTHORING_INTENT_KINDS,
    ArtifactFingerprintV1,
    AuthoringBuildProvenanceV1,
    AuthoringCompileResultV1,
    AuthoringDiagnosticV1,
    AuthoringPlanResultV1,
    AuthoringRequestV1,
    ProcessIRScriptLanguageV1,
    ProcessIRStateReferenceV1,
    ProcessIRStateEffectDeclarationV1,
    ProcessIRMapEffectDeclarationV1,
    ProcessIRScriptEffectDeclarationV1,
    ProcessIRSubprocessEffectDeclarationV1,
    ProcessIRExternalWriterDeclarationV1,
    ProcessIREffectDeclarationsV1,
    AuthoringRevisionBindingV1,
    CapabilityGapV1,
    ComponentDependencyEdgeV1,
    DecisionResolutionV1,
    IntegrationSpecAuthoringIntentV1,
    LiveDeploymentComparisonV1,
    ProcessCfgSummaryV1,
    ProcessIRAuthoringIntentV1,
    RecipeAuthoringIntentV1,
    RecipeInvocationRequestV1,
    RequiredDecisionV1,
    ResolvedReferenceSummaryV1,
    TopologyParticipantV1,
    TopologyRelationSummaryV1,
    ValidationReportSummaryV1,
    authoring_build_provenance_v1_json_schema,
    authoring_compile_result_v1_json_schema,
    authoring_plan_result_v1_json_schema,
    authoring_request_v1_json_schema,
    authoring_revision_binding_v1_json_schema,
    canonical_authoring_json,
    sort_authoring_diagnostics,
)

__all__ = [
    'IntegrationSpecV1',
    'IntegrationComponentSpec',
    # Process component envelope/unit contracts (issue #153). The INTERNAL
    # materialization plan lives in authoring/process_materialization.py and is
    # deliberately NOT exported — it is apply's own record, not a caller shape.
    'ProcessAuthoringUnitV1',
    'ProcessComponentEnvelopeV1',
    'ProcessConnectionOverrideV1',
    'ProcessExtensionBindingsV1',
    'ProcessOverrideFieldV1',
    'PipelineSpec',
    'StageSpec',
    'PipelineEdgeSpec',
    'PipelineStageKind',
    'PipelineEdgeKind',
    'StageCardinality',
    'StageContextEffect',
    'StageSideEffect',
    'StageFailureBehavior',
    # ProcessIRV1 (issue #136) — the private _process_ir_compat codec is
    # deliberately NOT exported.
    'PROCESS_IR_AUTHORING_CONTRACT_VERSION',
    'PROCESS_IR_V1_CAPABILITIES',
    'ProcessIRAuthoringContractEntryV1',
    'ProcessIRAuthoringContractPageV1',
    'process_ir_authoring_contract_v1_json_schema',
    'PROCESS_IR_VERSION',
    'BranchLegV1',
    'BranchNodeV1',
    'CacheGetNodeV1',
    'CachePutNodeV1',
    'CacheRemoveNodeV1',
    'CombineDocumentsOpV1',
    'ComponentRefV1',
    'ConnectorCallNodeV1',
    'CurrentPropertySourceV1',
    'CustomScriptingOpV1',
    'DataProcessNodeV1',
    'DataProcessOperationV1',
    'DdpPropertySourceV1',
    'DecisionFalseArmV1',
    'DecisionNodeV1',
    'DecisionOperandV1',
    'DecisionTrueArmV1',
    'DocumentCacheRetrieveNodeV1',
    'DppPropertySourceV1',
    'ErrorScopeV1',
    'ExceptionNodeV1',
    'FlowControlNodeV1',
    'IdempotencyContractRefV1',
    'IdempotencyEvidenceV1',
    'KeyReferenceIdempotencyV1',
    'LinearNodeV1',
    'MapRefNodeV1',
    'MessageNodeV1',
    'ProcessCallNodeV1',
    'ProcessIRDiagnostic',
    'ProcessIRV1',
    'ProcessIRValidationError',
    'ProcessNodeV1',
    'ProfilePropertySourceV1',
    'PropertySourceV1',
    'RetryPolicyV1',
    'ReturnDocumentsNodeV1',
    'SequenceNodeV1',
    'SetDdpNodeV1',
    'SetDppNodeV1',
    'SourceEndpointV1',
    'SplitDocumentsOpV1',
    'StaticOperandV1',
    'StaticPropertySourceV1',
    'StopNodeV1',
    'TargetEndpointV1',
    'TrackOperandV1',
    'TryCatchBodyStepV1',
    'TryCatchCatchBodyV1',
    'TryCatchNodeV1',
    'TryCatchTryBodyV1',
    'VerifiedActionIdempotencyV1',
    'canonical_process_ir_json',
    'canonical_process_ir_schema_json',
    'parse_process_ir_v1',
    'process_ir_v1_json_schema',
    # SystemTopologySpecV1 (issue #144) — planning-only, dark. The planner
    # package is deliberately NOT exported through boomi_mcp.models.
    'SYSTEM_TOPOLOGY_VERSION',
    'TOPOLOGY_OBJECT_KINDS',
    'TOPOLOGY_RELATION_KINDS',
    'TOPOLOGY_RELATION_ROLES',
    'ApiServiceObjectV1',
    'ApiServiceRouteRelationV1',
    'DeploymentBindingRelationV1',
    'DeploymentUnitObjectV1',
    'DocumentCacheObjectV1',
    'DocumentCacheUseRelationV1',
    'EnvironmentObjectV1',
    'EventStreamReferenceRelationV1',
    'ExternalEventStreamObjectV1',
    'ExternalQueueObjectV1',
    'OpaquePlatformRefV1',
    'ProcessCallRelationV1',
    'ProcessObjectV1',
    'ProcessPropertyObjectV1',
    'ProcessPropertyUseRelationV1',
    'QueueReferenceRelationV1',
    'RuntimeObjectV1',
    'ScheduleBindingRelationV1',
    'ScheduleObjectV1',
    'SystemTopologyDiagnostic',
    'SystemTopologySpecV1',
    'SystemTopologyValidationError',
    'TopologyComponentRefV1',
    'TopologyObjectKeyV1',
    'TopologyObjectV1',
    'TopologyRelationKeyV1',
    'TopologyRelationV1',
    'canonical_system_topology_json',
    'canonical_system_topology_schema_json',
    'parse_system_topology_v1',
    'system_topology_v1_json_schema',
    # Typed recipe contributions (issue #145) — the four contribution models and
    # their parse/canonical/schema helpers. The recipe REGISTRY and ENGINE live
    # in boomi_mcp.recipes and are deliberately not exported here.
    'RECIPE_COMPONENT_TYPES',
    'RECIPE_CONTRIBUTION_KINDS',
    'RECIPE_CONTRIBUTION_VERSION',
    'RECIPE_EXCLUDED_COMPONENT_TYPES',
    'AddTopologyObjectV1',
    'AddTopologyRelationV1',
    'AppendRootTerminalLegV1',
    'ComponentContributionV1',
    'ConstraintCheckV1',
    'ConstraintRequirementV1',
    'InsertRootLinearStepV1',
    'ProcessIRPatchOperationV1',
    'ProcessIRPatchV1',
    'RecipeComponentKey',
    'RecipeComponentType',
    'RecipeContributionV1',
    'RecipeContributionValidationError',
    'RecipeSemanticId',
    'RequireCapabilityV1',
    'RequireComponentV1',
    'RequireProcessV1',
    'RequireTopologyObjectV1',
    'RequireTopologyRelationV1',
    'SetProcessRootV1',
    'SystemTopologyPatchOperationV1',
    'SystemTopologyPatchV1',
    'canonical_recipe_contribution_json',
    'canonical_recipe_contribution_schema_json',
    'canonical_recipe_contributions_json',
    'parse_recipe_contribution',
    'recipe_contribution_v1_json_schema',
    'scan_forbidden_recipe_shape',
    'validate_contribution_object',
    # MCP authoring contracts (issue #146) — the typed request, the two
    # read-only results, and their schema helpers. The boomi_mcp.authoring
    # orchestration package is deliberately not exported here.
    'AUTHORING_ACTIONS',
    'AUTHORING_CONTRACT_VERSION',
    'AUTHORING_INTENT_KINDS',
    'ArtifactFingerprintV1',
    'AuthoringBuildProvenanceV1',
    'AuthoringCompileResultV1',
    'AuthoringDiagnosticV1',
    'AuthoringPlanResultV1',
    'AuthoringRequestV1',
    'ProcessIRScriptLanguageV1',
    'ProcessIRStateReferenceV1',
    'ProcessIRStateEffectDeclarationV1',
    'ProcessIRMapEffectDeclarationV1',
    'ProcessIRScriptEffectDeclarationV1',
    'ProcessIRSubprocessEffectDeclarationV1',
    'ProcessIRExternalWriterDeclarationV1',
    'ProcessIREffectDeclarationsV1',
    'AuthoringRevisionBindingV1',
    'CapabilityGapV1',
    'ComponentDependencyEdgeV1',
    'DecisionResolutionV1',
    'IntegrationSpecAuthoringIntentV1',
    'LiveDeploymentComparisonV1',
    'ProcessCfgSummaryV1',
    'ProcessIRAuthoringIntentV1',
    'RecipeAuthoringIntentV1',
    'RecipeInvocationRequestV1',
    'RequiredDecisionV1',
    'ResolvedReferenceSummaryV1',
    'TopologyParticipantV1',
    'TopologyRelationSummaryV1',
    'ValidationReportSummaryV1',
    'authoring_build_provenance_v1_json_schema',
    'authoring_compile_result_v1_json_schema',
    'authoring_plan_result_v1_json_schema',
    'authoring_request_v1_json_schema',
    'authoring_revision_binding_v1_json_schema',
    'canonical_authoring_json',
    'sort_authoring_diagnostics',
]
