"""The identifier grammars, pinned against sources the implementation did not author.

Fixture provenance, which is the whole point of this module's test design:

* POSITIVES come from executed captures under ``docs/architecture/evidence/issue-155``
  — ids the PLATFORM minted for executions that ran green. They are not written by
  hand here and not generated by the code under test.
* NEGATIVES come from ``docs/spec/platformOpenAPISv3.0.3.json`` — the platform's own
  published API description. The most valuable one is its documented example for an
  execution id, which is UNDATED and which a fixture author would naturally copy.

Both directions are pinned. A grammar that accepted everything would pass the
positives; a grammar that accepted nothing would pass the negatives.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import pytest

from boomi_mcp.connector_replay.ids import (
    BOOMI_COMPONENT_ID_PATTERN,
    EXECUTION_ID_PATTERN,
    is_boomi_component_id,
    is_execution_id,
)

_REPO = Path(__file__).resolve().parents[1]
_CAPTURES = _REPO / "docs" / "architecture" / "evidence" / "issue-155" / "captures"
_SPEC = _REPO / "docs" / "spec" / "platformOpenAPISv3.0.3.json"

_EXECUTION_ID_IN_TEXT = re.compile(r"execution-[0-9a-fA-F-]+-\d{4}\.\d{2}\.\d{2}")


def _platform_minted_execution_ids() -> set[str]:
    """Every execution id the platform minted, read out of the archived captures."""
    found: set[str] = set()
    for path in _CAPTURES.rglob("*execution_record*.json"):
        found.update(_EXECUTION_ID_IN_TEXT.findall(path.read_text()))
    return found


def _spec_text() -> str | None:
    """The platform spec, or None where it is not present.

    It is GITIGNORED, so it exists on a development machine and on no clone —
    including CI. A provenance guard that hard-fails without it converts "the
    provenance cannot be re-verified here" into "the behaviour is untested here",
    which is backwards: the behavioural assertion is the one that must always run.
    So provenance is re-checked wherever the spec exists, and the behaviour is
    checked everywhere.
    """
    try:
        return _SPEC.read_text()
    except OSError:
        return None


def test_the_capture_corpus_is_large_enough_to_be_evidence():
    """A corpus this test derives from an archive must be asserted non-empty.

    If the captures move or are renamed, every positive assertion below would
    become vacuously true while still reporting green. Assert a floor, not merely
    that the set is truthy.
    """
    ids = _platform_minted_execution_ids()
    assert len(ids) >= 50, (
        "expected the archived captures to supply a substantial execution-id "
        "corpus; found {0}. If the archive moved, fix the path rather than "
        "lowering this floor — a shrinking corpus silently weakens every "
        "positive case below.".format(len(ids))
    )


def test_every_platform_minted_execution_id_is_accepted():
    rejected = sorted(i for i in _platform_minted_execution_ids() if not is_execution_id(i))
    assert rejected == [], (
        "the grammar rejects ids the platform actually minted: {0}".format(rejected)
    )


def test_the_platforms_own_undated_example_is_rejected():
    """The documented example carries no date, and no real execution id looks like it.

    This is the case a hand-written fixture reaches for, which is exactly why it
    is the one worth pinning: a grammar with an optional date passes every
    positive above and still admits this.
    """
    undated = "execution-110b23f4-567a-8d90-1234-56789e0b123d"
    spec = _spec_text()
    if spec is not None:
        assert undated in spec, (
            "this test's negative is supposed to be the platform's OWN documented "
            "example; it is no longer present in the spec, so the pin has lost its "
            "provenance and must be re-derived rather than hard-coded"
        )
    assert not is_execution_id(undated)


def test_a_different_object_sharing_the_prefix_is_rejected():
    other = "executionrecord-110b23f4-567a-8d90-1234-56789e0b123d"
    spec = _spec_text()
    if spec is not None:
        assert other in spec
    assert not is_execution_id(other)


@pytest.mark.parametrize(
    "value",
    [
        "",
        "execution-",
        "not-an-execution-id",
        # right shape, wrong separator between uuid and date
        "execution-110b23f4-567a-8d90-1234-56789e0b123d.2026.08.27",
        # a real id with trailing whitespace: anchored, so rejected
        "execution-1957bb8f-9a89-4254-b169-9ddbf41fddf8-2026.08.26 ",
        # a real id embedded in a larger string
        "see execution-1957bb8f-9a89-4254-b169-9ddbf41fddf8-2026.08.26 for detail",
        None,
        42,
    ],
)
def test_execution_id_negatives(value):
    assert not is_execution_id(value)


def test_the_two_component_id_grammars_answer_different_questions():
    """A reference is validated for well-formedness; a citation, against observation.

    One lowercase-only pattern was tried for both and was wrong. The general
    grammar serves callers supplying a certificate or profile reference, and UUIDs
    are case-insensitive — a previous review round established that with a test,
    which this broke and which caught it. The strict grammar serves evidence rows,
    where the question is not "is this well-formed?" but "is this an id the
    platform was observed to mint?"
    """
    from boomi_mcp.connector_replay.ids import is_evidence_component_id

    lower = "c4016c66-1234-4abc-9def-0123456789ab"
    upper = lower.upper()

    # A reference may be either case.
    assert is_boomi_component_id(lower)
    assert is_boomi_component_id(upper)

    # A citation may not.
    assert is_evidence_component_id(lower)
    assert not is_evidence_component_id(upper)

    # Both stay anchored.
    for check in (is_boomi_component_id, is_evidence_component_id):
        assert not check(lower + " ")
        assert not check("x" + lower)
        assert not check(lower[:-1])
        assert not check(None)
    assert not is_boomi_component_id(lower + " ")
    assert not is_boomi_component_id("x" + lower)
    assert not is_boomi_component_id(lower[:-1])
    assert not is_boomi_component_id(None)


def test_component_ids_in_the_archive_are_accepted():
    """Real component ids, read from captured component XML rather than invented."""
    seen: set[str] = set()
    for path in _CAPTURES.rglob("operation_component.xml"):
        seen.update(re.findall(r'componentId="([^"]+)"', path.read_text()))
        seen.update(re.findall(r'\bid="([0-9a-fA-F-]{36})"', path.read_text()))
    assert seen, "no component ids found in the archived component XML"
    rejected = sorted(i for i in seen if not is_boomi_component_id(i))
    assert rejected == [], "grammar rejects real component ids: {0}".format(rejected)


def test_the_patterns_are_anchored_at_both_ends():
    """A structural pin: an unanchored id grammar matches substrings.

    Both languages are used to CLASSIFY untrusted values, so a pattern that
    matched a prefix would accept a longer string carrying an id plus arbitrary
    trailing content.
    """
    for pattern in (BOOMI_COMPONENT_ID_PATTERN, EXECUTION_ID_PATTERN):
        assert pattern.startswith("^"), pattern
        assert pattern.endswith("$"), pattern
